name: Run downloader
env:
  DENO_DIR: ~/.deno_cache

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest  
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno dependencies 
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Run downloader
        env: 
          PIKPAK_PASSWORD: ${{ secrets.PIKPAK_PASSWORD }}
          PIKPAK_USER: ${{ secrets.PIKPAK_USER }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          deno task run
          # date +"%Y-%m-%dT%H:%M:%S%z" > ./data/.last-run
      - name: Commits Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The commit message for the commit.
          commit_message: "Update database"
          commit_author: Author <actions@github.com>
          
